/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane;
import model.Figure;
import model.Direction;
/**
 *
 * @author Fabian
 */
public class MainGUI extends javax.swing.JFrame {

    ArrayList<Figure> figures;
    Controller co;

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        setTitle("Menue");
        super.pack();
        setLocation(100,100);
        co = new Controller();
        co.addFigures();
        figures = co.getFigures();
        movementPanel1.setBackground(Color.BLACK);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movementPanel1 = new view.MovementPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                onKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                onKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout movementPanel1Layout = new javax.swing.GroupLayout(movementPanel1);
        movementPanel1.setLayout(movementPanel1Layout);
        movementPanel1Layout.setHorizontalGroup(
            movementPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        movementPanel1Layout.setVerticalGroup(
            movementPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(movementPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_onKeyPressed
     if(evt.getKeyCode() == KeyEvent.VK_RIGHT)
     {
         Graphics2D g2d = (Graphics2D)movementPanel1.getGraphics();
         co.start("HansPeter", g2d, Direction.right);
     }else if(evt.getKeyCode() == KeyEvent.VK_LEFT)
     {
         Graphics2D g2d = (Graphics2D)movementPanel1.getGraphics();
         co.start("HansPeter", g2d, Direction.left);
     }else if(evt.getKeyCode() == KeyEvent.VK_UP)
     {
          Graphics2D g2d = (Graphics2D)movementPanel1.getGraphics();
         co.start("HansPeter", g2d, Direction.up);
     }else if(evt.getKeyCode() == KeyEvent.VK_DOWN)
     {
          Graphics2D g2d = (Graphics2D)movementPanel1.getGraphics();
         co.start("HansPeter", g2d, Direction.down);
     }
    }//GEN-LAST:event_onKeyPressed

    private void onKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_onKeyReleased
     if(evt.getKeyCode() == KeyEvent.VK_RIGHT || evt.getKeyCode() == KeyEvent.VK_LEFT ||
        evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN)
     {
         co.stop("HansPeter");
     }
    }//GEN-LAST:event_onKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.MovementPanel movementPanel1;
    // End of variables declaration//GEN-END:variables
}
