/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.*;

/**
 *
 * @author Lukas
 */
public class MainMenuPanel extends javax.swing.JPanel
{

    /**
     * Creates new form MainMenuPanel
     */
    public MainMenuPanel()
    {
        initComponents();
        pLogo.add(new LogoPanel());
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        pButtons = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pLogo = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pButtons.setLayout(new java.awt.GridLayout(0, 1, 0, 4));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Singleplayer");
        pButtons.add(jButton1);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Multiplayer");
        pButtons.add(jButton2);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Editor");
        pButtons.add(jButton3);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Options");
        pButtons.add(jButton4);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Quit");
        pButtons.add(jButton5);

        jPanel1.add(pButtons);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pLogo.setLayout(new java.awt.BorderLayout());
        jPanel2.add(pLogo);

        add(jPanel2, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pButtons;
    private javax.swing.JPanel pLogo;
    // End of variables declaration//GEN-END:variables
}
